### ISSUE TITLE
Implement ServiceState class

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/zerorobot#7]
A service state is a list of 3 thing.
- category
- tag
- state

as an example, here is what a service state could look like in yaml. Root key is the category, then it contains a list of tags and the attached state.
```yaml
data:
   - db: ok
network:
   - local-tcp-443: ok
   - remote-http-80: ok
 process:
   - mongodb: ok
```

The ServiceState class should implement an API to work with this category,tag,state concept and some method to serialize/deserialize to/from a file.
